name: main
# This workflow is triggered on pushes to the repository.
on: [pull_request]

jobs:
  build:
    name: PR check
    # This job runs on Linux
    runs-on: 'ubuntu-latest'
    steps:
      - name: Self-Run              # Self-run the action against OGBot PRs as an "integration test".
        uses: ./
        with:
          token: ${{ github.token }}
