name: main
# This workflow is triggered on pushes to the repository.
on: [pull_request]

jobs:
  build:
    # Job name is Greeting
    name: Check
    # This job runs on Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'      # This step prints an output (time) from the previous step's action.
      - run: npm ci # Clean install. See: https://docs.npmjs.com/cli/v10/commands/npm-ci
      - name: Validate
        run: node index.js
