name: main
# This workflow is triggered on pushes to the repository.
on: [pull_request]

jobs:
  build:
    name: PR check
    # This job runs on Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'      # This step prints an output (time) from the previous step's action.
      - name: Self-Run              # Self-run the action against OGBot PRs as an "integration test".
        uses: ./
        with:
          token: ${{ github.token }}
